//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 07/07/2018 23:00:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace HjaContext
{

    [DatabaseAttribute(Name = "hja")]
    [ProviderAttribute(typeof(Devart.Data.PostgreSql.Linq.Provider.PgSqlDataProvider))]
    public partial class HjaDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(HjaDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertMedicamento(Medicamento instance);
        partial void UpdateMedicamento(Medicamento instance);
        partial void DeleteMedicamento(Medicamento instance);
        partial void InsertPersona(Persona instance);
        partial void UpdatePersona(Persona instance);
        partial void DeletePersona(Persona instance);
        partial void InsertRol(Rol instance);
        partial void UpdateRol(Rol instance);
        partial void DeleteRol(Rol instance);
        partial void InsertPersonaRol(PersonaRol instance);
        partial void UpdatePersonaRol(PersonaRol instance);
        partial void DeletePersonaRol(PersonaRol instance);

        #endregion

        public HjaDataContext() :
        base(GetConnectionString("HjaDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public HjaDataContext(MappingSource mappingSource) :
        base(GetConnectionString("HjaDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName +"\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public HjaDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public HjaDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public HjaDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public HjaDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<Medicamento> Medicamentos
        {
            get
            {
                return this.GetTable<Medicamento>();
            }
        }

        public Devart.Data.Linq.Table<Persona> Personas
        {
            get
            {
                return this.GetTable<Persona>();
            }
        }

        public Devart.Data.Linq.Table<Rol> Rols
        {
            get
            {
                return this.GetTable<Rol>();
            }
        }

        public Devart.Data.Linq.Table<PersonaRol> PersonaRols
        {
            get
            {
                return this.GetTable<PersonaRol>();
            }
        }
    }
}

namespace HjaContext
{

    /// <summary>
    /// There are no comments for HjaContext.Medicamento in the schema.
    /// </summary>
    [Table(Name = @"hja.medicamento")]
    public partial class Medicamento : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _Id;

        private string _Descripcion;

        private string _Codigo;

        private string _Clave;

        private System.Nullable<long> _EncargadoId;
        #pragma warning restore 0649

        private EntityRef<Persona> _Persona;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        partial void OnDescripcionChanging(string value);
        partial void OnDescripcionChanged();
        partial void OnCodigoChanging(string value);
        partial void OnCodigoChanged();
        partial void OnClaveChanging(string value);
        partial void OnClaveChanged();
        partial void OnEncargadoIdChanging(System.Nullable<long> value);
        partial void OnEncargadoIdChanged();
        #endregion

        public Medicamento()
        {
            this._Persona  = default(EntityRef<Persona>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", CanBeNull = false, DbType = "INT8 NOT NULL", IsPrimaryKey = true)]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        [Column(Name = @"descripcion", Storage = "_Descripcion", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                if (this._Descripcion != value)
                {
                    this.OnDescripcionChanging(value);
                    this.SendPropertyChanging("Descripcion");
                    this._Descripcion = value;
                    this.SendPropertyChanged("Descripcion");
                    this.OnDescripcionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Codigo in the schema.
        /// </summary>
        [Column(Name = @"codigo", Storage = "_Codigo", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                if (this._Codigo != value)
                {
                    this.OnCodigoChanging(value);
                    this.SendPropertyChanging("Codigo");
                    this._Codigo = value;
                    this.SendPropertyChanged("Codigo");
                    this.OnCodigoChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Clave in the schema.
        /// </summary>
        [Column(Name = @"clave", Storage = "_Clave", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Clave
        {
            get
            {
                return this._Clave;
            }
            set
            {
                if (this._Clave != value)
                {
                    this.OnClaveChanging(value);
                    this.SendPropertyChanging("Clave");
                    this._Clave = value;
                    this.SendPropertyChanged("Clave");
                    this.OnClaveChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EncargadoId in the schema.
        /// </summary>
        [Column(Name = @"encargado_id", Storage = "_EncargadoId", DbType = "INT8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> EncargadoId
        {
            get
            {
                return this._EncargadoId;
            }
            set
            {
                if (this._EncargadoId != value)
                {
                    if (this._Persona.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnEncargadoIdChanging(value);
                    this.SendPropertyChanging("EncargadoId");
                    this._EncargadoId = value;
                    this.SendPropertyChanged("EncargadoId");
                    this.OnEncargadoIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Persona in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Persona_Medicamento", Storage="_Persona", ThisKey="EncargadoId", OtherKey="Id", IsForeignKey=true)]
        public Persona Persona
        {
            get
            {
                return this._Persona.Entity;
            }
            set
            {
                Persona previousValue = this._Persona.Entity;
                if ((previousValue != value) || (this._Persona.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging("Persona");
                    if (previousValue != null)
                    {
                        this._Persona.Entity = null;
                        previousValue.Medicamentos.Remove(this);
                    }
                    this._Persona.Entity = value;
                    if (value != null)
                    {
                        this._EncargadoId = value.Id;
                        value.Medicamentos.Add(this);
                    }
                    else
                    {
                        this._EncargadoId = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("Persona");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for HjaContext.Persona in the schema.
    /// </summary>
    [Table(Name = @"hja.persona")]
    public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _Id;

        private string _Nombre;

        private string _ApellidoUno;

        private string _ApellidoDos;

        private string _Cedula;

        private string _Telefono;

        private string _Correo;

        private string _Clave;

        private System.Nullable<bool> _Entrada;
        #pragma warning restore 0649

        private EntitySet<Medicamento> _Medicamentos;

        private EntitySet<PersonaRol> _PersonaRols;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        partial void OnApellidoUnoChanging(string value);
        partial void OnApellidoUnoChanged();
        partial void OnApellidoDosChanging(string value);
        partial void OnApellidoDosChanged();
        partial void OnCedulaChanging(string value);
        partial void OnCedulaChanged();
        partial void OnTelefonoChanging(string value);
        partial void OnTelefonoChanged();
        partial void OnCorreoChanging(string value);
        partial void OnCorreoChanged();
        partial void OnClaveChanging(string value);
        partial void OnClaveChanged();
        partial void OnEntradaChanging(System.Nullable<bool> value);
        partial void OnEntradaChanged();
        #endregion

        public Persona()
        {
            this._Medicamentos = new EntitySet<Medicamento>(new Action<Medicamento>(this.attach_Medicamentos), new Action<Medicamento>(this.detach_Medicamentos));
            this._PersonaRols = new EntitySet<PersonaRol>(new Action<PersonaRol>(this.attach_PersonaRols), new Action<PersonaRol>(this.detach_PersonaRols));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT8 NOT NULL", IsPrimaryKey = true)]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        [Column(Name = @"nombre", Storage = "_Nombre", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                if (this._Nombre != value)
                {
                    this.OnNombreChanging(value);
                    this.SendPropertyChanging("Nombre");
                    this._Nombre = value;
                    this.SendPropertyChanged("Nombre");
                    this.OnNombreChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ApellidoUno in the schema.
        /// </summary>
        [Column(Name = @"apellido_uno", Storage = "_ApellidoUno", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string ApellidoUno
        {
            get
            {
                return this._ApellidoUno;
            }
            set
            {
                if (this._ApellidoUno != value)
                {
                    this.OnApellidoUnoChanging(value);
                    this.SendPropertyChanging("ApellidoUno");
                    this._ApellidoUno = value;
                    this.SendPropertyChanged("ApellidoUno");
                    this.OnApellidoUnoChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ApellidoDos in the schema.
        /// </summary>
        [Column(Name = @"apellido_dos", Storage = "_ApellidoDos", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string ApellidoDos
        {
            get
            {
                return this._ApellidoDos;
            }
            set
            {
                if (this._ApellidoDos != value)
                {
                    this.OnApellidoDosChanging(value);
                    this.SendPropertyChanging("ApellidoDos");
                    this._ApellidoDos = value;
                    this.SendPropertyChanged("ApellidoDos");
                    this.OnApellidoDosChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Cedula in the schema.
        /// </summary>
        [Column(Name = @"cedula", Storage = "_Cedula", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Cedula
        {
            get
            {
                return this._Cedula;
            }
            set
            {
                if (this._Cedula != value)
                {
                    this.OnCedulaChanging(value);
                    this.SendPropertyChanging("Cedula");
                    this._Cedula = value;
                    this.SendPropertyChanged("Cedula");
                    this.OnCedulaChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Telefono in the schema.
        /// </summary>
        [Column(Name = @"telefono", Storage = "_Telefono", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Telefono
        {
            get
            {
                return this._Telefono;
            }
            set
            {
                if (this._Telefono != value)
                {
                    this.OnTelefonoChanging(value);
                    this.SendPropertyChanging("Telefono");
                    this._Telefono = value;
                    this.SendPropertyChanged("Telefono");
                    this.OnTelefonoChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Correo in the schema.
        /// </summary>
        [Column(Name = @"correo", Storage = "_Correo", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Correo
        {
            get
            {
                return this._Correo;
            }
            set
            {
                if (this._Correo != value)
                {
                    this.OnCorreoChanging(value);
                    this.SendPropertyChanging("Correo");
                    this._Correo = value;
                    this.SendPropertyChanged("Correo");
                    this.OnCorreoChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Clave in the schema.
        /// </summary>
        [Column(Name = @"clave", Storage = "_Clave", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Clave
        {
            get
            {
                return this._Clave;
            }
            set
            {
                if (this._Clave != value)
                {
                    this.OnClaveChanging(value);
                    this.SendPropertyChanging("Clave");
                    this._Clave = value;
                    this.SendPropertyChanged("Clave");
                    this.OnClaveChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Entrada in the schema.
        /// </summary>
        [Column(Name = @"entrada", Storage = "_Entrada", DbType = "BOOL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<bool> Entrada
        {
            get
            {
                return this._Entrada;
            }
            set
            {
                if (this._Entrada != value)
                {
                    this.OnEntradaChanging(value);
                    this.SendPropertyChanging("Entrada");
                    this._Entrada = value;
                    this.SendPropertyChanged("Entrada");
                    this.OnEntradaChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Medicamentos in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Persona_Medicamento", Storage="_Medicamentos", ThisKey="Id", OtherKey="EncargadoId", DeleteRule="NO ACTION")]
        public EntitySet<Medicamento> Medicamentos
        {
            get
            {
                return this._Medicamentos;
            }
            set
            {
                this._Medicamentos.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for PersonaRols in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Persona_PersonaRol", Storage="_PersonaRols", ThisKey="Id", OtherKey="PersonaId", DeleteRule="NO ACTION")]
        public EntitySet<PersonaRol> PersonaRols
        {
            get
            {
                return this._PersonaRols;
            }
            set
            {
                this._PersonaRols.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Medicamentos(Medicamento entity)
        {
            this.SendPropertyChanging("Medicamentos");
            entity.Persona = this;
        }
    
        private void detach_Medicamentos(Medicamento entity)
        {
            this.SendPropertyChanging("Medicamentos");
            entity.Persona = null;
        }

        private void attach_PersonaRols(PersonaRol entity)
        {
            this.SendPropertyChanging("PersonaRols");
            entity.Persona = this;
        }
    
        private void detach_PersonaRols(PersonaRol entity)
        {
            this.SendPropertyChanging("PersonaRols");
            entity.Persona = null;
        }
    }

    /// <summary>
    /// There are no comments for HjaContext.Rol in the schema.
    /// </summary>
    [Table(Name = @"hja.rol")]
    public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _Id;

        private string _RolNombre;
        #pragma warning restore 0649

        private EntitySet<PersonaRol> _PersonaRols;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        partial void OnRolNombreChanging(string value);
        partial void OnRolNombreChanged();
        #endregion

        public Rol()
        {
            this._PersonaRols = new EntitySet<PersonaRol>(new Action<PersonaRol>(this.attach_PersonaRols), new Action<PersonaRol>(this.detach_PersonaRols));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT8 NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for RolNombre in the schema.
        /// </summary>
        [Column(Name = @"rol_nombre", Storage = "_RolNombre", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string RolNombre
        {
            get
            {
                return this._RolNombre;
            }
            set
            {
                if (this._RolNombre != value)
                {
                    this.OnRolNombreChanging(value);
                    this.SendPropertyChanging("RolNombre");
                    this._RolNombre = value;
                    this.SendPropertyChanged("RolNombre");
                    this.OnRolNombreChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PersonaRols in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Rol_PersonaRol", Storage="_PersonaRols", ThisKey="Id", OtherKey="RolId", DeleteRule="NO ACTION")]
        public EntitySet<PersonaRol> PersonaRols
        {
            get
            {
                return this._PersonaRols;
            }
            set
            {
                this._PersonaRols.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_PersonaRols(PersonaRol entity)
        {
            this.SendPropertyChanging("PersonaRols");
            entity.Rol = this;
        }
    
        private void detach_PersonaRols(PersonaRol entity)
        {
            this.SendPropertyChanging("PersonaRols");
            entity.Rol = null;
        }
    }

    /// <summary>
    /// There are no comments for HjaContext.PersonaRol in the schema.
    /// </summary>
    [Table(Name = @"hja.persona_rol")]
    public partial class PersonaRol : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _Id;

        private System.Nullable<long> _PersonaId;

        private System.Nullable<long> _RolId;
        #pragma warning restore 0649

        private EntityRef<Persona> _Persona;

        private EntityRef<Rol> _Rol;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        partial void OnPersonaIdChanging(System.Nullable<long> value);
        partial void OnPersonaIdChanged();
        partial void OnRolIdChanging(System.Nullable<long> value);
        partial void OnRolIdChanged();
        #endregion

        public PersonaRol()
        {
            this._Persona  = default(EntityRef<Persona>);
            this._Rol  = default(EntityRef<Rol>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", CanBeNull = false, DbType = "INT8 NOT null", IsPrimaryKey = true)]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PersonaId in the schema.
        /// </summary>
        [Column(Name = @"persona_id", Storage = "_PersonaId", DbType = "INT8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> PersonaId
        {
            get
            {
                return this._PersonaId;
            }
            set
            {
                if (this._PersonaId != value)
                {
                    if (this._Persona.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPersonaIdChanging(value);
                    this.SendPropertyChanging("PersonaId");
                    this._PersonaId = value;
                    this.SendPropertyChanged("PersonaId");
                    this.OnPersonaIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for RolId in the schema.
        /// </summary>
        [Column(Name = @"rol_id", Storage = "_RolId", DbType = "INT8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> RolId
        {
            get
            {
                return this._RolId;
            }
            set
            {
                if (this._RolId != value)
                {
                    if (this._Rol.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnRolIdChanging(value);
                    this.SendPropertyChanging("RolId");
                    this._RolId = value;
                    this.SendPropertyChanged("RolId");
                    this.OnRolIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Persona in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Persona_PersonaRol", Storage="_Persona", ThisKey="PersonaId", OtherKey="Id", IsForeignKey=true)]
        public Persona Persona
        {
            get
            {
                return this._Persona.Entity;
            }
            set
            {
                Persona previousValue = this._Persona.Entity;
                if ((previousValue != value) || (this._Persona.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging("Persona");
                    if (previousValue != null)
                    {
                        this._Persona.Entity = null;
                        previousValue.PersonaRols.Remove(this);
                    }
                    this._Persona.Entity = value;
                    if (value != null)
                    {
                        this._PersonaId = value.Id;
                        value.PersonaRols.Add(this);
                    }
                    else
                    {
                        this._PersonaId = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("Persona");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Rol in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Rol_PersonaRol", Storage="_Rol", ThisKey="RolId", OtherKey="Id", IsForeignKey=true)]
        public Rol Rol
        {
            get
            {
                return this._Rol.Entity;
            }
            set
            {
                Rol previousValue = this._Rol.Entity;
                if ((previousValue != value) || (this._Rol.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging("Rol");
                    if (previousValue != null)
                    {
                        this._Rol.Entity = null;
                        previousValue.PersonaRols.Remove(this);
                    }
                    this._Rol.Entity = value;
                    if (value != null)
                    {
                        this._RolId = value.Id;
                        value.PersonaRols.Add(this);
                    }
                    else
                    {
                        this._RolId = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("Rol");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
